return {
    apps = {
        Finder = '󰀶',
        WezTerm = '',
        Arc = '',
        ['Google Chrome'] = '',
        ['Толк'] = '',
        ['Календарь'] = '',
        ['Spark Desktop'] = '󰇮',
        Telegram = '',
        Mattermost = '󰭹',
        AMessenger = '󰭹',
        DBeaver = '',
        TablePlus = '',
        Code = '󰨞',
        Tunnelblick = '󱠽',
        Emacs = '',
        Zen = '',
        Obsidian = '󱓧',
        Spotify = '',
        Postman = '',
    },

    windows = {
        ['1'] = '󰼏',
        ['2'] = '󰼐',
        ['3'] = '󰼑',
        ['4'] = '󰼒',
        ['5'] = '󰼓',
        ['6'] = '󰼔',
        ['7'] = '󰼕',
        ['8'] = '󰼖',
        ['9'] = '󰼗',
        ['10'] = '󰿪',
    },
}
