export ZSH="/Users/alex/.oh-my-zsh"
ZSH_THEME="willsem"
plugins=(git zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

alias l="exa -lahgG"
alias ll="exa -lhgG"
alias lt="exa -lahg --tree"
alias llt="exa -lhg --tree"
alias tmux="env TERM=screen-256color tmux"
alias size="du -sh * | sort -h"
alias cls="clear"

export CMAKE_PREFIX_PATH=/usr/local/opt/qt5/
export EDITOR='nvim'
export VISUAL='nvim'
export VK_LAYER_PATH=/macOS/etc/vulkan/explicit_layers.d
export VK_ICD_FILENAMES=/macOS/etc/vulkan/icd.d/MoltenVK_icd.json
export PATH="$PATH:/usr/local/Cellar/llvm/9.0.1/bin"
